version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "/"
      - "/fpx"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "tokio-tungstenite"

      # these two need to be updated together so prevent dependabot from updating just one of each
      - dependency-name: "tower"
      - dependency-name: "axum"
    groups:
      cargo-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      actions-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch
