[advisories]
ignore = []
yanked = "deny"

[licenses]
allow = [
    "Unicode-3.0",
    "Apache-2.0",
    "MIT",
    "ISC",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
    "MPL-2.0",
    "OpenSSL",

    # "0BSD",
    # "Apache-2.0 WITH LLVM-exception",
    # "BSD-2-Clause",
    # "CC0-1.0",
    # "Unlicense",
    # "WTFPL",
    # "Zlib",
]
confidence-threshold = 0.8
exceptions = []

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore = true

[bans]
multiple-versions = "allow"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
