packages:
  - "studio"
  - "api"
  - "apps/fp-services"
  - "apps/honc-code-gen"
  - "apps/webhonc"
  - "playground"
  - "lilo/*"
  - "packages/*"
  - "examples/*"
  - "examples/service-bindings/*"
  - "www"
