packages:
  - "apps/studio/studio-frontend"
  - "apps/studio/studio-api"
  - "apps/fp-services"
  - "apps/honc-code-gen"
  - "apps/webhonc"
  - "playground"
  - "packages/*"
  - "examples/*"
  - "examples/service-bindings/*"
  - "www"
