packages:
  - "studio"
  - "api"
  - "fp-services"
  - "honc-code-gen"
  - "playground"
  - "workeroni"
  - "lilo/*"
  - "packages/*"
  - "examples/*"
  - "examples/service-bindings/*"
  - "webhonc"
  - "www"
