[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
url = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tracing = { workspace = true }
typeshare-core = { version = "1.9" }
schemars = { workspace = true }
fpx = { path = "../fpx" }
serde = { workspace = true }
serde_json = { workspace = true }
