name = "fpx-workers"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-30"

[[durable_objects.bindings]]
name = "WEBSOCKET_HIBERNATION_SERVER"
class_name = "WebSocketHibernationServer"

[[d1_databases]]
binding = "DB"
database_name = "DB"
database_id = "34c863ae-42ac-4cbe-9446-d5b6b274eb2c"

[build]
command = "cargo install -q worker-build && worker-build --release"
watch_dir = [
    "src",
    "migrations",
    "Cargo.toml",
    "../fpx-lib",
    "../fpx-macros",
    "../Cargo.toml",
    "../Cargo.lock",
]

[[migrations]]
tag = "v1"
new_classes = ["WebSocketHibernationServer"]

[vars]
AUTH_TOKEN = "your-secret-token-here"
