name = "fpx-workers"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-30"

[[durable_objects.bindings]]
name = "WEBSOCKET_HIBERNATION_SERVER"
class_name = "WebSocketHibernationServer"

[[d1_databases]]
binding = "DB"
database_name = "DB"
database_id = "c6a49b5e-b1c9-4cee-8c91-3440c5bd3233"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketHibernationServer"]
