---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp:
    endpoint: http://localhost:6767

  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]

  telemetry:
    logs:
      level: "debug"
