import { createContext } from "react";
import { Theme } from "..";

// TODO (Oscar): add default values for all the theme properties
export const defaultChartTheme: Theme = {
  axisColor: "#000",
  axisFontFamily: "sans-serif",
  axisFontSize: "12px",
  axisFontStyle: "normal",
  axisFontWeight: "normal",
  axisLetterSpacing: "0",
  buttonActiveBackgroundColor: "",
  buttonActiveColor: "",
  buttonBackgroundColor: "",
  buttonBackgroundColorActive: "",
  buttonBackgroundColorDisabled: "",
  buttonBorderRadius: "",
  buttonColor: "",
  buttonDisabledBackgroundColor: "",
  buttonDisabledColor: "",
  buttonFocusBackgroundColor: "",
  buttonFocusBorderColor: "",
  buttonFocusColor: "",
  buttonFocusOutline: "",
  buttonFont: "",
  buttonHoverBackgroundColor: "",
  buttonHoverColor: "",
  eventColor: "#000",
  gridStrokeColor: "#000",
  legendItemBorderRadius: "0",
  legendItemCheckboxBorderRadius: "0",
  legendItemCheckboxColor: "#000",
  legendItemColor: "",
  legendItemEmphasisBackgroundColor: "#000",
  legendItemEmphasisBorderRadius: "0",
  legendItemEmphasisColor: "",
  legendItemEmphasisFont: "",
  legendItemFont: "sans-serif",
  legendItemOnHoverBackgroundColor: "#000",
  legendItemOnHoverColor: "#000",
  legendResultsColor: "",
  legendResultsFont: "",
  legendResultsLetterSpacing: "",
  shapeListColors: ["#000"],
  targetLatencyColor: "#000",
};

export const ChartThemeContext = createContext<Theme>(defaultChartTheme);
