name = "goose-quotes"
compatibility_date = "2024-07-23"
compatibility_flags = [ "nodejs_compat" ]

# [dev]
# port = 3001

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "GOOSE_AVATARS"
bucket_name = "goose-avatars"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"