/* GENERATED BY FIGMA PLUGIN. PLEASE DO NOT MODIFY */

export const theme = {
  color: {
    support: {
      danger: {
        50: "var(--color-support-danger-50)",
        400: "var(--color-support-danger-400)",
        500: "var(--color-support-danger-500)",
        600: "var(--color-support-danger-600)",
        alpha: {
          50: "var(--color-support-danger-alpha-50)",
          200: "var(--color-support-danger-alpha-200)",
          300: "var(--color-support-danger-alpha-300)",
        },
      },
      warning: {
        50: "var(--color-support-warning-50)",
        400: "var(--color-support-warning-400)",
        500: "var(--color-support-warning-500)",
        600: "var(--color-support-warning-600)",
        alpha: {
          50: "var(--color-support-warning-alpha-50)",
        },
      },
      success: {
        50: "var(--color-support-success-50)",
        400: "var(--color-support-success-400)",
        500: "var(--color-support-success-500)",
        600: "var(--color-support-success-600)",
        alpha: {
          50: "var(--color-support-success-alpha-50)",
        },
      },
    },
    accent: {
      mustard: {
        100: "var(--color-accent-mustard-100)",
        300: "var(--color-accent-mustard-300)",
        500: "var(--color-accent-mustard-500)",
        700: "var(--color-accent-mustard-700)",
        900: "var(--color-accent-mustard-900)",
        alpha: {
          200: "var(--color-accent-mustard-alpha-200)",
          300: "var(--color-accent-mustard-alpha-300)",
        },
      },
      rust: {
        100: "var(--color-accent-rust-100)",
        300: "var(--color-accent-rust-300)",
        500: "var(--color-accent-rust-500)",
        700: "var(--color-accent-rust-700)",
        900: "var(--color-accent-rust-900)",
        alpha: {
          300: "var(--color-accent-rust-alpha-300)",
        },
      },
      magenta: {
        100: "var(--color-accent-magenta-100)",
        300: "var(--color-accent-magenta-300)",
        500: "var(--color-accent-magenta-500)",
        700: "var(--color-accent-magenta-700)",
        900: "var(--color-accent-magenta-900)",
        alpha: {
          300: "var(--color-accent-magenta-alpha-300)",
        },
      },
    },
    neutral: {
      50: "var(--color-neutral-50)",
      100: "var(--color-neutral-100)",
      200: "var(--color-neutral-200)",
      300: "var(--color-neutral-300)",
      400: "var(--color-neutral-400)",
      500: "var(--color-neutral-500)",
      600: "var(--color-neutral-600)",
      700: "var(--color-neutral-700)",
      800: "var(--color-neutral-800)",
      900: "var(--color-neutral-900)",
      alpha: {
        light: {
          100: "var(--color-neutral-alpha-light-100)",
          200: "var(--color-neutral-alpha-light-200)",
          400: "var(--color-neutral-alpha-light-400)",
        },
        dark: {
          300: "var(--color-neutral-alpha-dark-300)",
        },
      },
      black: "var(--color-neutral-black)",
      white: "var(--color-neutral-white)",
    },
    primary: {
      grape: {
        200: "var(--color-primary-grape-200)",
        400: "var(--color-primary-grape-400)",
        500: "var(--color-primary-grape-500)",
        600: "var(--color-primary-grape-600)",
        alpha: {
          50: "var(--color-primary-grape-alpha-50)",
          100: "var(--color-primary-grape-alpha-100)",
          200: "var(--color-primary-grape-alpha-200)",
          300: "var(--color-primary-grape-alpha-300)",
          400: "var(--color-primary-grape-alpha-400)",
        },
      },
    },
    border: {
      warning: "var(--color-border-warning)",
      success: "var(--color-border-success)",
      danger: "var(--color-border-danger)",
      default: "var(--color-border-default)",
      primary: "var(--color-border-primary)",
      muted: "var(--color-border-muted)",
    },
    fg: {
      warning: "var(--color-fg-warning)",
      danger: "var(--color-fg-danger)",
      success: "var(--color-fg-success)",
      accent: {
        1: "var(--color-fg-accent-1)",
        2: "var(--color-fg-accent-2)",
        3: "var(--color-fg-accent-3)",
      },
      muted: "var(--color-fg-muted)",
      onemphasis: {
        default: "var(--color-fg-onemphasis-default)",
        subtle: "var(--color-fg-onemphasis-subtle)",
      },
      subtle: "var(--color-fg-subtle)",
      default: "var(--color-fg-default)",
      primary: "var(--color-fg-primary)",
    },
    input: {
      border: "var(--color-input-border)",
      fg: {
        placeholder: "var(--color-input-fg-placeholder)",
        input: "var(--color-input-fg-input)",
      },
      bg: "var(--color-input-bg)",
    },
    bg: {
      disabled: "var(--color-bg-disabled)",
      emphasis: {
        primary: "var(--color-bg-emphasis-primary)",
        default: "var(--color-bg-emphasis-default)",
        "primary-subtle": "var(--color-bg-emphasis-primary-subtle)",
      },
      elevated: {
        default: "var(--color-bg-elevated-default)",
        hover: "var(--color-bg-elevated-hover)",
      },
      hover: "var(--color-bg-hover)",
      warning: "var(--color-bg-warning)",
      accent: {
        1: "var(--color-bg-accent-1)",
        2: "var(--color-bg-accent-2)",
        3: "var(--color-bg-accent-3)",
      },
      danger: "var(--color-bg-danger)",
      subtle: "var(--color-bg-subtle)",
      success: "var(--color-bg-success)",
      default: "var(--color-bg-default)",
    },
    button: {
      primary: {
        bg: {
          disabled: "var(--color-button-primary-bg-disabled)",
          hover: "var(--color-button-primary-bg-hover)",
          default: "var(--color-button-primary-bg-default)",
        },
        fg: {
          default: "var(--color-button-primary-fg-default)",
          disabled: "var(--color-button-primary-fg-disabled)",
        },
      },
      secondary: {
        fg: "var(--color-button-secondary-fg)",
        bg: "var(--color-button-secondary-bg)",
        border: "var(--color-button-secondary-border)",
      },
    },
  },
  radius: {
    minimal: "var(--radius-minimal)",
    rounded: "var(--radius-rounded)",
    default: "var(--radius-default)",
  },
  metric: {
    selected: "var(--metric-selected)",
  },
  font: {
    headings: {
      h1: "var(--font-headings-h1)",
      h2: "var(--font-headings-h2)",
      h3: "var(--font-headings-h3)",
      h4: "var(--font-headings-h4)",
      h5: "var(--font-headings-h5)",
      h6: "var(--font-headings-h6)",
    },
    body: {
      xl: {
        regular: "var(--font-body-xl-regular)",
        medium: "var(--font-body-xl-medium)",
      },
      l: {
        regular: "var(--font-body-l-regular)",
        medium: "var(--font-body-l-medium)",
      },
      md: {
        regular: "var(--font-body-md-regular)",
        medium: "var(--font-body-md-medium)",
      },
      sm: {
        regular: "var(--font-body-sm-regular)",
        medium: "var(--font-body-sm-medium)",
      },
      xs: {
        regular: "var(--font-body-xs-regular)",
        medium: "var(--font-body-xs-medium)",
      },
    },
    buttons: {
      md: "var(--font-buttons-md)",
      sm: "var(--font-buttons-sm)",
    },
    code: {
      regular: "var(--font-code-regular)",
      medium: "var(--font-code-medium)",
    },
    display: {
      1: "var(--font-display-1)",
    },
  },
  effect: {
    focus: {
      primary: "var(--focus-primary)",
    },
    shadow: {
      xxs: "var(--shadow-xxs)",
      m: "var(--shadow-m)",
    },
  },
} as const;
