#:schema node_modules/wrangler/config-schema.json
name = "webhonc"
main = "src/index.ts"
compatibility_date = "2024-07-01"

[dev]
port = 3000

[[durable_objects.bindings]]
name = "WEBHONC"
class_name = "WebHonc"

[[migrations]]
tag = "v1"
new_classes = ["WebHonc"]

[env.preview]
[[env.preview.durable_objects.bindings]]
name = "WEBHONC"
class_name = "WebHonc"

[[env.preview.migrations]]
tag = "v1"
new_classes = ["WebHonc"]
