/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AgentsAgentIdImport } from './routes/agents.$agentId'
import { Route as AgentsAgentIdInstanceIdImport } from './routes/agents.$agentId.$instanceId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AgentsAgentIdRoute = AgentsAgentIdImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRoute,
} as any)

const AgentsAgentIdInstanceIdRoute = AgentsAgentIdInstanceIdImport.update({
  id: '/$instanceId',
  path: '/$instanceId',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdImport
      parentRoute: typeof rootRoute
    }
    '/agents/$agentId/$instanceId': {
      id: '/agents/$agentId/$instanceId'
      path: '/$instanceId'
      fullPath: '/agents/$agentId/$instanceId'
      preLoaderRoute: typeof AgentsAgentIdInstanceIdImport
      parentRoute: typeof AgentsAgentIdImport
    }
  }
}

// Create and export the route tree

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdInstanceIdRoute: typeof AgentsAgentIdInstanceIdRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdInstanceIdRoute: AgentsAgentIdInstanceIdRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/$agentId/$instanceId': typeof AgentsAgentIdInstanceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/$agentId/$instanceId': typeof AgentsAgentIdInstanceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/$agentId/$instanceId': typeof AgentsAgentIdInstanceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents/$agentId' | '/agents/$agentId/$instanceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents/$agentId' | '/agents/$agentId/$instanceId'
  id: '__root__' | '/' | '/agents/$agentId' | '/agents/$agentId/$instanceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/agents/$agentId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/agents/$agentId": {
      "filePath": "agents.$agentId.tsx",
      "children": [
        "/agents/$agentId/$instanceId"
      ]
    },
    "/agents/$agentId/$instanceId": {
      "filePath": "agents.$agentId.$instanceId.tsx",
      "parent": "/agents/$agentId"
    }
  }
}
ROUTE_MANIFEST_END */
