---
name: Audit

on:
  push:
    branches: ["**"]

    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/deny.toml"
      - ".github/workflows/audit.yaml"

  schedule:
    - cron: "23 1 * * *"

  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: EmbarkStudios/cargo-deny-action@v1
