# This workflow will be triggered by a GitHub pull-request.
---
  name: Build node packages
  
  on:
    pull_request:
      branches: ["*"]
    push:
      branches: ["main", "release-*"]
  
  env:
    CARGO_TERM_COLOR: always
    FORCE_COLOR: true
  
  jobs:
    build_packages:
      name: Build packages
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*
            cache: npm

        - name: Install dependencies
          run: npm ci --workspaces

        # HACK: Install Biome CLI for Linux due to npm bug with optional dependencies
        - name: Install Biome CLI for Linux
          run: npm install @biomejs/cli-linux-x64 --save-dev

        - name: Lint all workspaces
          run: npm run lint:ci --workspaces

        # HACK: Install rollup to make client-library build succeed due to npm bug with optional dependencies
        - name: Install Rollup for Linux
          run: npm install @rollup/rollup-linux-x64-gnu --save-dev

        # HACK: For some reason need to install swc bindings in CI too
        - name: Install swc
          run: npm install @swc/cli @swc/core @swc/plugin-transform-imports --save-dev

        # HACK: This is getting ridiculous, but we need the linux-x64 build for sharp
        - name: Install sharp
          run: npm install --os=linux --cpu=x64 sharp --save-dev

        - name: Build all workspaces
          run: npm run build --workspaces --if-present
