# Build the fpx app. This will only be published as a build artifact.
---
name: Build app
on:
  # Allow manual trigger
  workflow_dispatch:

  # Run on every push to main
  push:
    branches: ["main", "tauri-main", "tauri-ci"]

jobs:
  build-app:
    name: Create binary for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    # permissions:
    #   id-token: write
    #   contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          # - os: ubuntu-latest-8-cores
          #   target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest-8-cores
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest-8-cores'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          target: ${{ matrix.target }}
          rustflags: "" # Do not fail on warnings, so reset the default value to empty

      - name: Install dependencies
        run: pnpm install

      - name: Build fiberplane/fpx-types
        run: pnpm run build:types

      - name: Build fpx app
        uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "--target ${{ matrix.target }} --ci"

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          paths=$(echo '${{ steps.tauri.outputs.artifactPaths }}' | jq -c -r '.[]')

          for artifact in $paths; do
            if [[ -f $artifact ]]; then
              echo "Moving $artifact"
              mv $artifact artifacts
            else
              echo "Artifact not found: $artifact"
              ls -la $artifact
            fi
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fpx_${{ matrix.target }}
          if-no-files-found: error
          retention-days: 7
          path: artifacts
