name: Check and build the website
on:
  pull_request:
    branches:
      - "*"
    paths:
      - "www/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        env:
          CI: true

      - name: Lint website
        run: pnpm --filter www lint:ci

      - name: Build website
        run: pnpm build:www
